baseURL = "https://za-arthur.github.io/"
languageCode = "en-us"
title = "artur.zakirov"
theme = "hugo-theme-console"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "home/"
  url = ""

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"
  
  [[params.navlinks]]
  name = "presentations/"
  url = "presentations/"
